# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

services:
  postgres:
    image: postgres:13
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    options: >-
      --health-cmd="pg_isready -U postgres -d postgres"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=5

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'   # use the Node.js version you need
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Install dependencies and build'

# Initialise database schema (runs dbInit.js)
- script: |
    cd backend
    npm install
    node dbInit.js
  displayName: 'Initialize database schema'
  env:
    DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

# Run unit tests
- script: |
    cd frontend
    CI=true npm test -- --coverage --watchAll=false
  displayName: 'Run frontend unit tests'

# Archive backend files for deployment
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/backend'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/backend-$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive backend files'

# Publish backend artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend-$(Build.BuildId).zip'
    ArtifactName: 'backend'
    publishLocation: 'Container'
  displayName: 'Publish backend artifact'

# Deploy Backend to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'andrew-bennett10'  # TODO: Replace with your service connection name
    appType: 'webAppLinux'
    appName: 'PokeApp'  # TODO: Replace with your actual backend app service name
    package: '$(Build.ArtifactStagingDirectory)/backend-$(Build.BuildId).zip'
    runtimeStack: 'NODE|20-lts'
    startUpCommand: 'npm install && node server.js'
  displayName: 'Deploy backend to Azure App Service'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

# Publish frontend build artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/frontend/build'
    ArtifactName: 'frontend'
    publishLocation: 'Container'
  displayName: 'Publish frontend build artifact'
