# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

services:
  postgres:
    image: postgres:13
    env:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    options: >-
      --health-cmd="pg_isready -U testuser -d testdb"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=5

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'   # use the Node.js version you need
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Install dependencies and build'

# Initialise database schema (runs dbInit.js)
- script: |
    cd backend
    npm install pg
    node dbInit.js
  displayName: 'Initialize database schema'
  env:
    DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb  

# # Optional: run tests if you have them
# - script: |
#     cd frontend
#     CI=true npm test
#   displayName: 'Run tests'