version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U testuser -d testdb']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://testuser:testpassword@db:5432/testdb
    ports:
      - '3001:3001'
    command: sh -c "npm run db:init && npm start"

volumes:
  postgres-data:
