# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - PokeApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test backend
        working-directory: ./backend
        run: |
          npm install
          
      - name: npm install and build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./backend
          
      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: ./frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: ./backend
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_01CA714A98904D71927574DC6B2A4C73 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F3E97232983F453AB2EED2277F7EC3C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_945EE6D26CC240FA89ACD23BD5AD6EB7 }}

      - name: 'Deploy Backend to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PokeApp'
          slot-name: 'Production'
          package: ./backend
      
      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: ./frontend-build
      
      - name: 'Deploy Frontend to Azure Static Web App'
        id: deploy-to-static-webapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./frontend-build"
          skip_app_build: true
          